spring:
  data:
    mongodb:
      uri: mongodb://mongo:Eedbfa-6Ag6CEDb6Cfa6ahdGC1DbE6cf@monorail.proxy.rlwy.net:49716/admin 
  datasource:
    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:42740/railway
    username: postgres
    password: d2CEf4*aB3C6ecdfDBDgFFA*1gE*c535
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# BEARER TOKEN
custom:
  token:
    key: JbjaF2@tV$