spring:
  data:
    mongodb:
      uri: mongodb://mongo:Bdf-E6GE1fhAaDBa31EdC61G41A-gAGh@monorail.proxy.rlwy.net:54701/admin
      # uri: mongodb://localhost:54701/voiture
  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:55313/railway
    username: postgres
    password: ag2CBEegb6fBe1GdgAd6cbbDdF5cgac1
    # url: jdbc:postgresql://localhost:5432/voiture
    # username: postgres
    # password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# BEARER TOKEN
custom:
  token:
    key: JbjaF2@tV$