logging:
  level:
    root: DEBUG
    org:
      springframework:
        web: DEBUG
        data: DEBUG
        jpa: DEBUG
        google: DEBUG
        firebase: DEBUG
        firebaseAdmin: DEBUG

spring:
  data:
    mongodb:
      uri: mongodb://mongo:d6cHF4a-5ah1fffeG-E62fCacG6b1ff1@monorail.proxy.rlwy.net:19349/admin
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:51143/railway
    username: postgres
    password: -5dBC-e4BEdebabcEeD5DAB45GDG5e4b
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# BEARER TOKEN
custom:
  token:
    key: JbjaF2@tV$

# Firebase Credentials
gcp:
  firebase:
    service-account: classpath:firebase/carapp-1b62d-firebase-adminsdk-hn1bo-5bd3650983.json
  notifications:
    taille-max: 10
