spring:
  data:
    mongodb:
      uri: mongodb://nomena:root@localhost:27017/admin
  datasource:
    url: jdbc:postgresql://localhost:5433/voiture
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# BEARER TOKEN
custom:
  token:
    key: JbjaF2@tV$