logging:
  level:
    root: DEBUG
    org:
      springframework:
        web: DEBUG
        data: DEBUG
        jpa: DEBUG
        google: DEBUG
        firebase: DEBUG
        firebaseAdmin: DEBUG

spring:
  data:
    mongodb:
      #uri: mongodb://nomena:root@localhost:27017/admin
      uri: mongodb://mongo:3CBDBbAE3HH-a1FaDd1GBB5Gh-dHD5hd@viaduct.proxy.rlwy.net:59865/admin
  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:55313/railway
    #url: jdbc:postgresql://localhost:5432/voiture
    username: postgres
    #username: nomena
    password: ag2CBEegb6fBe1GdgAd6cbbDdF5cgac1
    #password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# BEARER TOKEN
custom:
  token:
    key: JbjaF2@tV$

# Firebase Credentials
gcp:
  firebase:
    service-account: classpath:firebase/carapp-1b62d-firebase-adminsdk-hn1bo-5bd3650983.json
  notifications:
    taille-max: 50
